server:
  port: 8004
  servlet:
    context-path: /api
spring:
  application:
    name: ai-agent
  ai:
    #大模型
    dashscope:
      api-key: xxxxxxxxxxxxxxxxxx  #替换为自己的API key
      chat:
        options:
          model: qwen-plus
  #设置环境为本地环境，不设置可以注释
  profiles:
    active: local
# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.hk.aiagent.controller
# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn
chat:
  fileName: system-love
  system_message: classpath:/prompts/${chat.fileName}.st
search:
  apiKey: xxxxxxxxxxxxx  #替换为自己   https://www.searchapi.io/ 的API key
logging:
  level:
    org.springframework.ai: DEBUG
tenxun:
  cos:
    config:
      host: xxxxxxxxxxxx  #替换为自己的cos地址
      secretId: xxxxxxxxxxxxx  #替换为自己的secretId
      secretKey: xxxxxxxxxxxxx  #替换为自己的secretKey
      bucket: xxxxxxxxxxxxx  #替换为自己的bucket
      region: xxxxxxxxxxxxx  #替换为自己的region
      timeOut: 60
